# Maintainer: ...
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

%package root-domain_SystemFW
Summary:	Tizen System Framework
Suggests:	resourced
Suggests:	deviced
%description root-domain_SystemFW
This domain, "System FW", introduces packages and sub-domains/features
of Tizen System-FW domain.
This is maintained by ...
%files root-domain_SystemFW
# Keep this empty


# END
