# Maintainer: TBD: This is temporary block for TDC Demo. You may proceed with this later anyway.
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

###########################
## Starter & Menu screen ##
###########################
%package sub1-domain_Feature-Starter
Summary:	Starter daemon and Menu screen App
Requires: starter
Requires: starter-profile_common
Requires: org.tizen.menu-screen
%description sub1-domain_Feature-Starter
Tizen block (set of packages) for supporting to display menu screen.
%files sub1-domain_Feature-Starter
