# Maintainer: TBD: This is temporary block for TDC Demo. You may proceed with this later anyway.
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

######################
## Docker Framework ##
######################
%package sub1-domain_Feature-Docker
Summary: Docker Framework
Requires: docker-launcher
Requires: docker-adaptor
Requires: docker-engine
%description sub1-domain_Feature-Docker
Tizen block (set of packages) for Docker Framework
%files sub1-domain_Feature-Docker
