# Maintainer: TBD: This is temporary block for TDC Demo. You may proceed with this later anyway.
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

############################
## Tizen Debug and Locale ##
############################
%package sub1-domain_Feature-Tool_And_Locale
Summary:	Tizen Debug tools and Locale
Suggests: crash-worker
Suggests: tizen-debug
Suggests: tizen-locale
Suggests: glibc-locale
Suggests: pam-locale
Suggests: memps
Suggests: psmisc
%description sub1-domain_Feature-Tool_And_Locale
Tizen block (set of packages) for supporting debug tools and locale for Tizen.
%files sub1-domain_Feature-Tool_And_Locale
