# Maintainer: TBD: This is temporary block for TDC Demo. You may proceed with this later anyway.
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

%package root-domain_WebAPI
Summary:	Tizen Web API Sets
Requires:	webapi-plugins
Suggests:	webapi-pluging-common
Suggests:	webapi-pluging-mobile
Suggests:	webapi-pluging-ivi
Suggests:	webapi-pluging-wearable
Suggests:	webapi-pluging-tv
%description root-domain_WebAPI
WebAPI Plugins
%files root-domain_WebAPI
