# Maintainer: TBD: This is temporary block for TDC Demo. You may proceed with this later anyway.
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

###################
## Tizen Upgrade ##
###################
%package sub1-domain_Feature-Upgrade
Summary:	Tizen Upgrade Feature
Requires: system-rw-update
%description sub1-domain_Feature-Upgrade
Tizen block (set of packages) for supporting to upgrade new tizen image.
%files sub1-domain_Feature-Upgrade
