# Maintainer: TBD: This is temporary block for TDC Demo. You may proceed with this later anyway.
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

###############
## IoT Setup ##
###############
%package sub1-domain_Feature-Setup
Summary:	Device Setup Feature
Requires: setup-adaptor
%description sub1-domain_Feature-Setup
Tizen block (set of packages) for supporting to setup device auto-configuration especially network.
%files sub1-domain_Feature-Setup
