# Maintainer: TBD: This is temporary block for TDC Demo. You may proceed with this later anyway.
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

############
## SoftAP ##
############
%package sub1-domain_Feature-SoftAP
Summary:	SoftAP feature packages
Requires: capi-network-softap
Requires: dnsmasq
Requires: iproute2
Requires: mobileap-agent
%description sub1-domain_Feature-SoftAP
Tizen block (set of packages) for supporting .NET of Tizen
%files sub1-domain_Feature-SoftAP
