# Maintainer: TBD: This is temporary block for TDC Demo. You may proceed with this later anyway.
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

############
## WebAPI ##
############
%package sub1-domain_Feature-WebAPI
Summary:	Web API feature packages
Requires: wrtjs
Requires: cordova-api
Requires: webapi-plugins
Requires: webapi-plugins-profile_common
Requires: wgt-backend
Requires: browser-provider
Requires: libwebsockets
%description sub1-domain_Feature-WebAPI
Tizen block (set of packages) for supporting WebAPI of Tizen
%files sub1-domain_Feature-WebAPI
