# Maintainer: TBD: This is temporary block for TDC Demo. You may proceed with this later anyway.
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

%package root-domain_API
Summary:	Tizen Native API Sets
Suggests:	%{name}-sub1-domain_API-Account_AccountManager
Suggests:	%{name}-sub1-domain_API-Account_FIDOClient
Suggests:	%{name}-sub1-domain_API-Account_OAuth2
Suggests:	%{name}-sub1-domain_API-Account_SyncManager
Suggests:	%{name}-sub1-domain_API-Account_libOAuth
Suggests:	%{name}-sub1-domain_API-AppFramework_Application
Suggests:	%{name}-sub1-domain_API-AppFramework_ApplicationManager
Suggests:	%{name}-sub1-domain_API-AppFramework_Badge
Suggests:	%{name}-sub1-domain_API-AppFramework_Bundle
Suggests:	%{name}-sub1-domain_API-AppFramework_DataControl
Suggests:	%{name}-sub1-domain_API-AppFramework_MessagePort
Suggests:	%{name}-sub1-domain_API-AppFramework_Notification
Suggests:	%{name}-sub1-domain_API-AppFramework_PackageManager
Suggests:	%{name}-sub1-domain_API-AppFramework_ServiceApplication
Suggests:	%{name}-sub1-domain_API-AppFramework_Shortcut
Suggests:	%{name}-sub1-domain_API-AppFramework_Widget
Suggests:	%{name}-sub1-domain_API-Content_Download
Suggests:	%{name}-sub1-domain_API-Content_MIMEType
Suggests:	%{name}-sub1-domain_API-Context_ActivityRecognition
Suggests:	%{name}-sub1-domain_API-Context_ContextualHistory
Suggests:	%{name}-sub1-domain_API-Context_ContextualTrigger
Suggests:	%{name}-sub1-domain_API-Context_GestureRecognition
Suggests:	%{name}-sub1-domain_API-Location
Suggests:	%{name}-sub1-domain_API-Maps
Suggests:	%{name}-sub1-domain_API-Messaging_Email
Suggests:	%{name}-sub1-domain_API-Messaging_Messages
Suggests:	%{name}-sub1-domain_API-Messaging_Push
Suggests:	%{name}-sub1-domain_API-Multimedia_AudioIO
Suggests:	%{name}-sub1-domain_API-Multimedia_Camera
Suggests:	%{name}-sub1-domain_API-Multimedia_ImageUtil
Suggests:	%{name}-sub1-domain_API-Multimedia_MediaCodec
Suggests:	%{name}-sub1-domain_API-Multimedia_MediaController
Suggests:	%{name}-sub1-domain_API-Multimedia_MediaDemuxer
Suggests:	%{name}-sub1-domain_API-Multimedia_MediaMuxer
Suggests:	%{name}-sub1-domain_API-Multimedia_MediaStreamer
Suggests:	%{name}-sub1-domain_API-Multimedia_MediaTool
Suggests:	%{name}-sub1-domain_API-Multimedia_MediaVision
Suggests:	%{name}-sub1-domain_API-Multimedia_MetadataEditor
Suggests:	%{name}-sub1-domain_API-Multimedia_MetadataExtractor
Suggests:	%{name}-sub1-domain_API-Multimedia_OpenAL
Suggests:	%{name}-sub1-domain_API-Multimedia_Player
Suggests:	%{name}-sub1-domain_API-Multimedia_Radio
Suggests:	%{name}-sub1-domain_API-Multimedia_Recorder
Suggests:	%{name}-sub1-domain_API-Multimedia_ScreenMirroring
Suggests:	%{name}-sub1-domain_API-Multimedia_SoundManager
Suggests:	%{name}-sub1-domain_API-Multimedia_StreamRecorder
Suggests:	%{name}-sub1-domain_API-Multimedia_ThumbnailUtil
Suggests:	%{name}-sub1-domain_API-Multimedia_TonePlayer
Suggests:	%{name}-sub1-domain_API-Multimedia_VideoUtil
Suggests:	%{name}-sub1-domain_API-Multimedia_WAVPlayer
Suggests:	%{name}-sub1-domain_API-Multimedia_libEXIF
Suggests:	%{name}-sub1-domain_API-Network_Bluetooth
Suggests:	%{name}-sub1-domain_API-Network_ASP
Suggests:	%{name}-sub1-domain_API-Network_Connection
Suggests:	%{name}-sub1-domain_API-Network_Curl
Suggests:	%{name}-sub1-domain_API-Network_DNSSD
Suggests:	%{name}-sub1-domain_API-Network_HTTP
Suggests:	%{name}-sub1-domain_API-Network_IoTCon
Suggests:	%{name}-sub1-domain_API-Network_MTP
Suggests:	%{name}-sub1-domain_API-Network_NFC
Suggests:	%{name}-sub1-domain_API-Network_SSDP
Suggests:	%{name}-sub1-domain_API-Network_Smartcard
Suggests:	%{name}-sub1-domain_API-Network_VPNService
Suggests:	%{name}-sub1-domain_API-Network_WiFi
Suggests:	%{name}-sub1-domain_API-Network_WiFiDirect
Suggests:	%{name}-sub1-domain_API-Security_CSR
Suggests:	%{name}-sub1-domain_API-Security_KeyManager
Suggests:	%{name}-sub1-domain_API-Security_OpenSSL
Suggests:	%{name}-sub1-domain_API-Security_YACA
Suggests:	%{name}-sub1-domain_API-Social_Calendar
Suggests:	%{name}-sub1-domain_API-Social_Contacts
Suggests:	%{name}-sub1-domain_API-Social_PhonenumberUtils
Suggests:	%{name}-sub1-domain_API-System_MediaKey
Suggests:	%{name}-sub1-domain_API-System_RuntimeInformation
Suggests:	%{name}-sub1-domain_API-System_Sensor
Suggests:	%{name}-sub1-domain_API-System_SystemInformation
Suggests:	%{name}-sub1-domain_API-System_dlog
Suggests:	%{name}-sub1-domain_API-Telephony
Suggests:	%{name}-sub1-domain_API-UI_Cairo
Suggests:	%{name}-sub1-domain_API-UI_ClipboardHistoryManager
Suggests:	%{name}-sub1-domain_API-UI_DALi
Suggests:	%{name}-sub1-domain_API-UI_EFL
Suggests:	%{name}-sub1-domain_API-UI_EFLUTIL
Suggests:	%{name}-sub1-domain_API-UI_EflExtension
Suggests:	%{name}-sub1-domain_API-UI_ExternalOutputManager
Suggests:	%{name}-sub1-domain_API-UI_FontConfig
Suggests:	%{name}-sub1-domain_API-UI_Freetype
Suggests:	%{name}-sub1-domain_API-UI_HarfBuzz
Suggests:	%{name}-sub1-domain_API-UI_SDL
Suggests:	%{name}-sub1-domain_API-UI_TBMSurface
Suggests:	%{name}-sub1-domain_API-UI_TizenWSShell
Suggests:	%{name}-sub1-domain_API-UI_UIViewManager
Suggests:	%{name}-sub1-domain_API-UIX_InputMethod
Suggests:	%{name}-sub1-domain_API-UIX_InputMethodManager
Suggests:	%{name}-sub1-domain_API-Web
%description root-domain_API
__EXPAND__: domains
Tizen packages blocked and sorted by API sets defined by TPL
%files root-domain_API


%package sub1-domain_API-Account_AccountManager
Summary:	Account - Account Manager
Requires:	libaccount-service
%description sub1-domain_API-Account_AccountManager
Tizen block (set of packages) for API sets of domain API-Account_AccountManager
%files sub1-domain_API-Account_AccountManager


%package sub1-domain_API-Account_FIDOClient
Summary:	Account - FIDO Client
Requires:	fido-client
%description sub1-domain_API-Account_FIDOClient
Tizen block (set of packages) for API sets of domain API-Account_FIDOClient
%files sub1-domain_API-Account_FIDOClient


%package sub1-domain_API-Account_OAuth2
Summary:	Account - OAuth
Requires:	oauth2
%description sub1-domain_API-Account_OAuth2
Tizen block (set of packages) for API sets of domain API-Account_OAuth2
%files sub1-domain_API-Account_OAuth2


%package sub1-domain_API-Account_SyncManager
Summary:	Account - Sync Manager
Requires:	libcore-sync-client
Suggests:	%{name}-sub2-domain_API-Account_SyncManager-SyncAdapter
%description sub1-domain_API-Account_SyncManager
Tizen block (set of packages) for API sets of domain API-Account_SyncManager
%files sub1-domain_API-Account_SyncManager


%package sub2-domain_API-Account_SyncManager-SyncAdapter
Summary:	Account - SyncManager - Sync Adapter
Requires:	libcore-sync-client
%description sub2-domain_API-Account_SyncManager-SyncAdapter
Tizen block (set of packages) for API sets of sub2-domain_API-Account_SyncManager-SyncAdapter
%files sub2-domain_API-Account_SyncManager-SyncAdapter


%package sub1-domain_API-Account_libOAuth
Summary:	Account - libOAuth
Requires:	liboauth
%description sub1-domain_API-Account_libOAuth
Tizen block (set of packages) for API sets of domain API-Account_libOAuth
%files sub1-domain_API-Account_libOAuth


%package sub1-domain_API-AppFramework_Application
Summary:	AppFramework - Application
Suggests:	%{name}-sub2-domain_API-AppFramework_Application-Alarm
Suggests:	%{name}-sub2-domain_API-AppFramework_Application-AppCommon
Suggests:	%{name}-sub2-domain_API-AppFramework_Application-AppControl
Suggests:	%{name}-sub2-domain_API-AppFramework_Application-Event
Suggests:	%{name}-sub2-domain_API-AppFramework_Application-Internationalization
Suggests:	%{name}-sub2-domain_API-AppFramework_Application-Preference
Suggests:	%{name}-sub2-domain_API-AppFramework_Application-ResourceManager
%description sub1-domain_API-AppFramework_Application
Tizen block (set of packages) for API sets of domain API-AppFramework_Application
%files sub1-domain_API-AppFramework_Application


%package sub2-domain_API-AppFramework_Application-Alarm
Summary:	AppFramework - Application - Alarm
Requires:	capi-appfw-alarm
%description sub2-domain_API-AppFramework_Application-Alarm
Tizen block (set of packages) for API sets of sub2-domain_API-AppFramework_Application-Alarm
%files sub2-domain_API-AppFramework_Application-Alarm


%package sub2-domain_API-AppFramework_Application-AppCommon
Summary:	AppFramework - Application - App Common
Requires:	capi-appfw-app-common
%description sub2-domain_API-AppFramework_Application-AppCommon
Tizen block (set of packages) for API sets of sub2-domain_API-AppFramework_Application-AppCommon
%files sub2-domain_API-AppFramework_Application-AppCommon


%package sub2-domain_API-AppFramework_Application-AppControl
Summary:	AppFramework - Application - App Control
Requires:	capi-appfw-application
%description sub2-domain_API-AppFramework_Application-AppControl
Tizen block (set of packages) for API sets of sub2-domain_API-AppFramework_Application-AppControl
%files sub2-domain_API-AppFramework_Application-AppControl


%package sub2-domain_API-AppFramework_Application-Event
Summary:	Appframework - Application - Event
Requires:	capi-appfw-event
%description sub2-domain_API-AppFramework_Application-Event
Tizen block (set of packages) for API sets of sub2-domain_API-AppFramework_Application-Event
%files sub2-domain_API-AppFramework_Application-Event


%package sub2-domain_API-AppFramework_Application-Internationalization
Summary:	AppFramework - Application - Internationalization
Requires:	capi-appfw-application
%description sub2-domain_API-AppFramework_Application-Internationalization
Tizen block (set of packages) for API sets of sub2-domain_API-AppFramework_Application-Internationalization
%files sub2-domain_API-AppFramework_Application-Internationalization


%package sub2-domain_API-AppFramework_Application-Preference
Summary:	AppFramework - Application - Preference
Requires:	capi-appfw-preference
%description sub2-domain_API-AppFramework_Application-Preference
Tizen block (set of packages) for API sets of sub2-domain_API-AppFramework_Application-Preference
%files sub2-domain_API-AppFramework_Application-Preference


%package sub2-domain_API-AppFramework_Application-ResourceManager
Summary:	AppFramework - Application - Resource Manager
Requires:	capi-appfw-app-common
%description sub2-domain_API-AppFramework_Application-ResourceManager
Tizen block (set of packages) for API sets of sub2-domain_API-AppFramework_Application-ResourceManager
%files sub2-domain_API-AppFramework_Application-ResourceManager


%package sub1-domain_API-AppFramework_ApplicationManager
Summary:	AppFramework - AppManager
Requires:	capi-appfw-app-manager
Requires:	amd
%description sub1-domain_API-AppFramework_ApplicationManager
Tizen block (set of packages) for API sets of domain API-AppFramework_ApplicationManager
%files sub1-domain_API-AppFramework_ApplicationManager


%package sub1-domain_API-AppFramework_Badge
Summary:	AppFramework - Badge
Requires:	badge
Requires:	data-provider-master
%description sub1-domain_API-AppFramework_Badge
Tizen block (set of packages) for API sets of domain API-AppFramework_Badge
%files sub1-domain_API-AppFramework_Badge


%package sub1-domain_API-AppFramework_Bundle
Summary:	AppFramework - Bundle
Requires:	bundle
%description sub1-domain_API-AppFramework_Bundle
Tizen block (set of packages) for API sets of domain API-AppFramework_Bundle
%files sub1-domain_API-AppFramework_Bundle


%package sub1-domain_API-AppFramework_DataControl
Summary:	AppFramework - DataControl
Requires:	data-control
Requires:	amd
%description sub1-domain_API-AppFramework_DataControl
Tizen block (set of packages) for API sets of domain API-AppFramework_DataControl
%files sub1-domain_API-AppFramework_DataControl


%package sub1-domain_API-AppFramework_MessagePort
Summary:	AppFramework - MessagePort
Requires:	message-port
Requires:	amd
%description sub1-domain_API-AppFramework_MessagePort
Tizen block (set of packages) for API sets of domain API-AppFramework_MessagePort
%files sub1-domain_API-AppFramework_MessagePort


%package sub1-domain_API-AppFramework_Notification
Summary:	AppFramework - Notification
Requires:	notification
Requires:	data-provider-master
%description sub1-domain_API-AppFramework_Notification
Tizen block (set of packages) for API sets of domain API-AppFramework_Notification
%files sub1-domain_API-AppFramework_Notification


%package sub1-domain_API-AppFramework_PackageManager
Summary:	AppFramework - Package Manager
Requires:	capi-appfw-package-manager
%description sub1-domain_API-AppFramework_PackageManager
Tizen block (set of packages) for API sets of domain API-AppFramework_PackageManager
%files sub1-domain_API-AppFramework_PackageManager


%package sub1-domain_API-AppFramework_ServiceApplication
Summary:	AppFramework - Service Application
Requires:	appcore-agent
%description sub1-domain_API-AppFramework_ServiceApplication
Tizen block (set of packages) for API sets of domain API-AppFramework_ServiceApplication
%files sub1-domain_API-AppFramework_ServiceApplication


%package sub1-domain_API-AppFramework_Shortcut
Summary:	AppFramework - Shortcut
Requires:	libshortcut
Requires:	data-provider-master
%description sub1-domain_API-AppFramework_Shortcut
Tizen block (set of packages) for API sets of domain API-AppFramework_Shortcut
%files sub1-domain_API-AppFramework_Shortcut


%package sub1-domain_API-AppFramework_Widget
Summary:	AppFramework - Widget
Suggests:	%{name}-sub2-domain_API-AppFramework_Widget-WidgetApplication
Suggests:	%{name}-sub2-domain_API-AppFramework_Widget-WidgetService
Suggests:	%{name}-sub2-domain_API-AppFramework_Widget-WidgetViewer
Suggests:	%{name}-sub2-domain_API-AppFramework_Widget-WidgetViewerDali
%description sub1-domain_API-AppFramework_Widget
Tizen block (set of packages) for API sets of domain API-AppFramework_Widget
%files sub1-domain_API-AppFramework_Widget


%package sub2-domain_API-AppFramework_Widget-WidgetApplication
Summary:	AppFramework - Widget - Widget Application
Requires:	appcore-widget
%description sub2-domain_API-AppFramework_Widget-WidgetApplication
Tizen block (set of packages) for API sets of sub2-domain_API-AppFramework_Widget-WidgetApplication
%files sub2-domain_API-AppFramework_Widget-WidgetApplication


%package sub2-domain_API-AppFramework_Widget-WidgetService
Summary:	AppFramework - Widget - Widget Service
Requires:	libwidget_service
%description sub2-domain_API-AppFramework_Widget-WidgetService
Tizen block (set of packages) for API sets of sub2-domain_API-AppFramework_Widget-WidgetService
%files sub2-domain_API-AppFramework_Widget-WidgetService


%package sub2-domain_API-AppFramework_Widget-WidgetViewer
Summary:	AppFramework - Widget - Widget Viewer
Requires:	libwidget_viewer_evas
%description sub2-domain_API-AppFramework_Widget-WidgetViewer
Tizen block (set of packages) for API sets of sub2-domain_API-AppFramework_Widget-WidgetViewer
%files sub2-domain_API-AppFramework_Widget-WidgetViewer


%package sub2-domain_API-AppFramework_Widget-WidgetViewerDali
Summary:	AppFramework - Widget - Widget Viewer Dali
Requires:	libwidget_viewer_dali
%description sub2-domain_API-AppFramework_Widget-WidgetViewerDali
Tizen block (set of packages) for API sets of sub2-domain_API-AppFramework_Widget-WidgetViewerDali
%files sub2-domain_API-AppFramework_Widget-WidgetViewerDali


%package sub1-domain_API-Content_Download
Summary:	Content - Download
Requires:	capi-web-url-download
Requires:	download-provider
%description sub1-domain_API-Content_Download
Tizen block (set of packages) for API sets of domain API-Content_Download
%files sub1-domain_API-Content_Download


%package sub1-domain_API-Content_MIMEType
Summary:	Content - MIME Type
Requires:	capi-content-mime-type
%description sub1-domain_API-Content_MIMEType
Tizen block (set of packages) for API sets of domain API-Content_MIMEType
%files sub1-domain_API-Content_MIMEType


%package sub1-domain_API-Context_ActivityRecognition
Summary:	Context - Activity Recognition
Requires:	capi-context-motion
Requires:	sensord
%description sub1-domain_API-Context_ActivityRecognition
Tizen block (set of packages) for API sets of domain API-Context_ActivityRecognition
%files sub1-domain_API-Context_ActivityRecognition


%package sub1-domain_API-Context_ContextualHistory
Summary:	Context - Contextual History
Requires:	capi-context
Requires:	context-app-history
%description sub1-domain_API-Context_ContextualHistory
Tizen block (set of packages) for API sets of domain API-Context_ContextualHistory
%files sub1-domain_API-Context_ContextualHistory


%package sub1-domain_API-Context_ContextualTrigger
Summary:	Context - Contextual Trigger
Requires:	capi-context
Requires:	context-job-scheduler
%description sub1-domain_API-Context_ContextualTrigger
Tizen block (set of packages) for API sets of domain API-Context_ContextualTrigger
%files sub1-domain_API-Context_ContextualTrigger


%package sub1-domain_API-Context_GestureRecognition
Summary:	Context - Gesture Recognition
Requires:	capi-context-motion
Requires:	sensord
%description sub1-domain_API-Context_GestureRecognition
Tizen block (set of packages) for API sets of domain API-Context_GestureRecognition
%files sub1-domain_API-Context_GestureRecognition


%package sub1-domain_API-Location
Summary:	Location
Requires:	capi-location-manager
Requires:	lbs-server
Suggests:	%{name}-sub2-domain_API-Location-Geofence
%description sub1-domain_API-Location
Tizen block (set of packages) for API sets of domain API-Location
%files sub1-domain_API-Location


%package sub2-domain_API-Location-Geofence
Summary:	Location - Geofence
Requires:	capi-geofence-manager
Requires:	geofence-server
%description sub2-domain_API-Location-Geofence
Tizen block (set of packages) for API sets of sub2-domain_API-Location-Geofence
%files sub2-domain_API-Location-Geofence


%package sub1-domain_API-Maps
Summary:	Maps
Requires:	capi-maps-service
Requires:	%{name}-sub2-domain_API-Maps-HEREPlugin
Requires:	%{name}-sub2-domain_API-Maps-MapzenPlugin
%description sub1-domain_API-Maps
Tizen block (set of packages) for API sets of domain API-Maps
%files sub1-domain_API-Maps


%package sub2-domain_API-Maps-HEREPlugin
Summary:	Maps - HERE Plugin
Requires:	maps-plugin-here
Requires:	heremaps-uc-launcher
Requires:	org.tizen.heremaps-uc
%description sub2-domain_API-Maps-HEREPlugin
Tizen block (set of packages) for API sets of sub2-domain_API-Maps-HEREPlugin
%files sub2-domain_API-Maps-HEREPlugin


%package sub2-domain_API-Maps-MapzenPlugin
Summary:	Maps - Mapzen Plugin
Requires:	maps-plugin-mapzen
%description sub2-domain_API-Maps-MapzenPlugin
Tizen block (set of packages) for API sets of sub2-domain_API-Maps-MapzenPlugin
%files sub2-domain_API-Maps-MapzenPlugin


%package sub1-domain_API-Messaging_Email
Summary:	Messaging - Email
Requires:	capi-messaging-email
%description sub1-domain_API-Messaging_Email
Tizen block (set of packages) for API sets of domain API-Messaging_Email
%files sub1-domain_API-Messaging_Email


%package sub1-domain_API-Messaging_Messages
Summary:	Messaging - Messages
Requires:	capi-messaging-messages
Requires:	msg-manager
Requires:	sms-plugin
Requires:	mms-plugin
Requires:	msg-service-tools
%description sub1-domain_API-Messaging_Messages
Tizen block (set of packages) for API sets of domain API-Messaging_Messages
%files sub1-domain_API-Messaging_Messages


%package sub1-domain_API-Messaging_Push
Summary:	Messaging - Push
Requires:	libpush
%description sub1-domain_API-Messaging_Push
Tizen block (set of packages) for API sets of domain API-Messaging_Push
%files sub1-domain_API-Messaging_Push



%package sub1-domain_API-Multimedia_AudioIO
Summary:	Multimedia - Audio I/O
Requires:	capi-media-audio-io
Requires:	capi-media-sound-manager
%description sub1-domain_API-Multimedia_AudioIO
Tizen block (set of packages) for API sets of domain API-Multimedia_AudioIO
%files sub1-domain_API-Multimedia_AudioIO


%package sub1-domain_API-Multimedia_Camera
Summary:	Multimedia - Camera
Requires:	capi-media-camera
Requires:	mmsvc-camera
Requires:	mused
%description sub1-domain_API-Multimedia_Camera
Tizen block (set of packages) for API sets of domain API-Multimedia_Camera
%files sub1-domain_API-Multimedia_Camera


%package sub1-domain_API-Multimedia_ImageUtil
Summary:	Multimedia - Image Util
Requires:	capi-media-image-util
%description sub1-domain_API-Multimedia_ImageUtil
Tizen block (set of packages) for API sets of domain API-Multimedia_ImageUtil
%files sub1-domain_API-Multimedia_ImageUtil


%package sub1-domain_API-Multimedia_MediaCodec
Summary:	Multimedia - Media Codec
Requires:	capi-media-codec
%description sub1-domain_API-Multimedia_MediaCodec
Tizen block (set of packages) for API sets of domain API-Multimedia_MediaCodec
%files sub1-domain_API-Multimedia_MediaCodec


%package sub1-domain_API-Multimedia_MediaController
Summary:	Multimedia - Media Controller
Requires:	capi-media-controller
%description sub1-domain_API-Multimedia_MediaController
Tizen block (set of packages) for API sets of domain API-Multimedia_MediaController
%files sub1-domain_API-Multimedia_MediaController


%package sub1-domain_API-Multimedia_MediaDemuxer
Summary:	Multimedia - Media Demuxer
Requires:	capi-mediamuxer
%description sub1-domain_API-Multimedia_MediaDemuxer
Tizen block (set of packages) for API sets of domain API-Multimedia_MediaDemuxer
%files sub1-domain_API-Multimedia_MediaDemuxer


%package sub1-domain_API-Multimedia_MediaMuxer
Summary:	Multimedia - Media Muxer
Requires:	capi-mediamuxer
%description sub1-domain_API-Multimedia_MediaMuxer
Tizen block (set of packages) for API sets of domain API-Multimedia_MediaMuxer
%files sub1-domain_API-Multimedia_MediaMuxer


%package sub1-domain_API-Multimedia_MediaStreamer
Summary:	Multimedia - Media Streamer
Requires:	capi-media-streamer
%description sub1-domain_API-Multimedia_MediaStreamer
Tizen block (set of packages) for API sets of domain API-Multimedia_MediaStreamer
%files sub1-domain_API-Multimedia_MediaStreamer


%package sub1-domain_API-Multimedia_MediaTool
Summary:	Multimedia - Media Tool
Requires:	capi-media-tool
%description sub1-domain_API-Multimedia_MediaTool
Tizen block (set of packages) for API sets of domain API-Multimedia_MediaTool
%files sub1-domain_API-Multimedia_MediaTool


%package sub1-domain_API-Multimedia_MediaVision
Summary:	Multimedia - Media Vision
Requires:	capi-media-vision
%description sub1-domain_API-Multimedia_MediaVision
Tizen block (set of packages) for API sets of domain API-Multimedia_MediaVision
%files sub1-domain_API-Multimedia_MediaVision


%package sub1-domain_API-Multimedia_MetadataEditor
Summary:	Multimedia - Metadata Editor
Requires:	capi-media-metadata-editor
%description sub1-domain_API-Multimedia_MetadataEditor
Tizen block (set of packages) for API sets of domain API-Multimedia_MetadataEditor
%files sub1-domain_API-Multimedia_MetadataEditor


%package sub1-domain_API-Multimedia_MetadataExtractor
Summary:	Multimedia - Metadata Extractor
Requires:	capi-media-metadata-extractor
%description sub1-domain_API-Multimedia_MetadataExtractor
Tizen block (set of packages) for API sets of domain API-Multimedia_MetadataExtractor
%files sub1-domain_API-Multimedia_MetadataExtractor


%package sub1-domain_API-Multimedia_OpenAL
Summary:	Multimedia - OpenAL
Requires:	openal-soft
Requires:	capi-media-sound-manager
%description sub1-domain_API-Multimedia_OpenAL
Tizen block (set of packages) for API sets of domain API-Multimedia_OpenAL
%files sub1-domain_API-Multimedia_OpenAL


%package sub1-domain_API-Multimedia_Player
Summary:	Multimedia - Player
Requires:	capi-media-player
%description sub1-domain_API-Multimedia_Player
Tizen block (set of packages) for API sets of domain API-Multimedia_Player
%files sub1-domain_API-Multimedia_Player


%package sub1-domain_API-Multimedia_Radio
Summary:	Multimedia - Radio
Requires:	capi-media-radio
%description sub1-domain_API-Multimedia_Radio
Tizen block (set of packages) for API sets of domain API-Multimedia_Radio
%files sub1-domain_API-Multimedia_Radio


%package sub1-domain_API-Multimedia_Recorder
Summary:	Multimedia - Recorder
Requires:	capi-media-recorder
%description sub1-domain_API-Multimedia_Recorder
Tizen block (set of packages) for API sets of domain API-Multimedia_Recorder
%files sub1-domain_API-Multimedia_Recorder


%package sub1-domain_API-Multimedia_ScreenMirroring
Summary:	Multimedia - Screen Mirroring
Requires:	capi-media-screen-mirroring
%description sub1-domain_API-Multimedia_ScreenMirroring
Tizen block (set of packages) for API sets of domain API-Multimedia_ScreenMirroring
%files sub1-domain_API-Multimedia_ScreenMirroring


%package sub1-domain_API-Multimedia_SoundManager
Summary:	Multimedia - Sound Manager
Requires:	capi-media-sound-manager
%description sub1-domain_API-Multimedia_SoundManager
Tizen block (set of packages) for API sets of domain API-Multimedia_SoundManager
%files sub1-domain_API-Multimedia_SoundManager


%package sub1-domain_API-Multimedia_StreamRecorder
Summary:	Multimedia - StreamRecorder
Requires:	capi-media-streamrecorder
%description sub1-domain_API-Multimedia_StreamRecorder
Tizen block (set of packages) for API sets of domain API-Multimedia_StreamRecorder
%files sub1-domain_API-Multimedia_StreamRecorder


%package sub1-domain_API-Multimedia_ThumbnailUtil
Summary:	Multimedia - Thumbnail Util
Requires:	capi-media-thumbnail-util
%description sub1-domain_API-Multimedia_ThumbnailUtil
Tizen block (set of packages) for API sets of domain API-Multimedia_ThumbnailUtil
%files sub1-domain_API-Multimedia_ThumbnailUtil


%package sub1-domain_API-Multimedia_TonePlayer
Summary:	Multimedia - Tone Player
Requires:	capi-media-tone-player
%description sub1-domain_API-Multimedia_TonePlayer
Tizen block (set of packages) for API sets of domain API-Multimedia_TonePlayer
%files sub1-domain_API-Multimedia_TonePlayer


%package sub1-domain_API-Multimedia_VideoUtil
Summary:	Multimedia - Video Util
Requires:	capi-media-video-util
%description sub1-domain_API-Multimedia_VideoUtil
Tizen block (set of packages) for API sets of domain API-Multimedia_VideoUtil
%files sub1-domain_API-Multimedia_VideoUtil


%package sub1-domain_API-Multimedia_WAVPlayer
Summary:	Multimedia - WAV Player
Requires:	capi-media-wav-player
%description sub1-domain_API-Multimedia_WAVPlayer
Tizen block (set of packages) for API sets of domain API-Multimedia_WAVPlayer
%files sub1-domain_API-Multimedia_WAVPlayer


%package sub1-domain_API-Multimedia_libEXIF
Summary:	Multimedia - libEXIF
Requires:	libexif
%description sub1-domain_API-Multimedia_libEXIF
Tizen block (set of packages) for API sets of domain API-Multimedia_libEXIF
%files sub1-domain_API-Multimedia_libEXIF


%package sub1-domain_API-Network_Bluetooth
Summary:	Network - Bluetooth
Suggests:	%{name}-sub2-domain_API-Network_Bluetooth-BluetoothAVRCP
Suggests:	%{name}-sub2-domain_API-Network_Bluetooth-BluetoothAdapter
Suggests:	%{name}-sub2-domain_API-Network_Bluetooth-BluetoothAudio
Suggests:	%{name}-sub2-domain_API-Network_Bluetooth-BluetoothDevice
Suggests:	%{name}-sub2-domain_API-Network_Bluetooth-BluetoothGATT
Suggests:	%{name}-sub2-domain_API-Network_Bluetooth-BluetoothGATTServer
Suggests:	%{name}-sub2-domain_API-Network_Bluetooth-BluetoothHDP
Suggests:	%{name}-sub2-domain_API-Network_Bluetooth-BluetoothHID
Suggests:	%{name}-sub2-domain_API-Network_Bluetooth-BluetoothLEAdapter
Suggests:	%{name}-sub2-domain_API-Network_Bluetooth-BluetoothOPP
Suggests:	%{name}-sub2-domain_API-Network_Bluetooth-BluetoothSocket
%description sub1-domain_API-Network_Bluetooth
Tizen block (set of packages) for API sets of domain API-Network_Bluetooth
%files sub1-domain_API-Network_Bluetooth


%package sub2-domain_API-Network_Bluetooth-BluetoothAVRCP
Summary:	Network - Bluetooth - Bluetooth AVRCP
Requires:	capi-network-bluetooth
Requires:	bluez
Requires:	bluetooth-tools
Suggests:	bluetooth-frimware-bcm
Suggests:	bluetooth-firmware-sprd
%description sub2-domain_API-Network_Bluetooth-BluetoothAVRCP
Tizen block (set of packages) for API sets of sub2-domain_API-Network_Bluetooth-BluetoothAVRCP
%files sub2-domain_API-Network_Bluetooth-BluetoothAVRCP


%package sub2-domain_API-Network_Bluetooth-BluetoothAdapter
Summary:	Network - Bluetooth - Bluetooth Adapter
Requires:	capi-network-bluetooth
Requires:	bluez
Requires:	bluetooth-tools
Suggests:	bluetooth-frimware-bcm
Suggests:	bluetooth-firmware-sprd
%description sub2-domain_API-Network_Bluetooth-BluetoothAdapter
Tizen block (set of packages) for API sets of sub2-domain_API-Network_Bluetooth-BluetoothAdapter
%files sub2-domain_API-Network_Bluetooth-BluetoothAdapter


%package sub2-domain_API-Network_Bluetooth-BluetoothAudio
Summary:	Network - Bluetooth - Bluetooth Audio
Requires:	capi-network-bluetooth
Requires:	bluez
Requires:	bluetooth-tools
Requires:	bluetooth-agent
Suggests:	bluetooth-frimware-bcm
Suggests:	bluetooth-firmware-sprd
%description sub2-domain_API-Network_Bluetooth-BluetoothAudio
Tizen block (set of packages) for API sets of sub2-domain_API-Network_Bluetooth-BluetoothAudio
%files sub2-domain_API-Network_Bluetooth-BluetoothAudio


%package sub2-domain_API-Network_Bluetooth-BluetoothDevice
Summary:	Network - Bluetooth - Bluetooth Device
Requires:	capi-network-bluetooth
Requires:	bluez
Requires:	bluetooth-tools
Suggests:	bluetooth-frimware-bcm
Suggests:	bluetooth-firmware-sprd
%description sub2-domain_API-Network_Bluetooth-BluetoothDevice
Tizen block (set of packages) for API sets of sub2-domain_API-Network_Bluetooth-BluetoothDevice
%files sub2-domain_API-Network_Bluetooth-BluetoothDevice


%package sub2-domain_API-Network_Bluetooth-BluetoothGATT
Summary:	Network - Bluetooth - Bluetooth GATT
Requires:	capi-network-bluetooth
Requires:	bluez
Requires:	bluetooth-tools
Suggests:	bluetooth-frimware-bcm
Suggests:	bluetooth-firmware-sprd
%description sub2-domain_API-Network_Bluetooth-BluetoothGATT
Tizen block (set of packages) for API sets of sub2-domain_API-Network_Bluetooth-BluetoothGATT
%files sub2-domain_API-Network_Bluetooth-BluetoothGATT


%package sub2-domain_API-Network_Bluetooth-BluetoothGATTServer
Summary:	Network - Bluetooth - Bluetooth GATT Server
Requires:	capi-network-bluetooth
Requires:	bluez
Requires:	bluetooth-tools
Suggests:	bluetooth-frimware-bcm
Suggests:	bluetooth-firmware-sprd
%description sub2-domain_API-Network_Bluetooth-BluetoothGATTServer
Tizen block (set of packages) for API sets of sub2-domain_API-Network_Bluetooth-BluetoothGATTServer
%files sub2-domain_API-Network_Bluetooth-BluetoothGATTServer


%package sub2-domain_API-Network_Bluetooth-BluetoothHDP
Summary:	Network - Bluetooth - Bluetooth HDP
Requires:	capi-network-bluetooth
Requires:	bluez
Requires:	bluetooth-tools
Suggests:	bluetooth-frimware-bcm
Suggests:	bluetooth-firmware-sprd
%description sub2-domain_API-Network_Bluetooth-BluetoothHDP
Tizen block (set of packages) for API sets of sub2-domain_API-Network_Bluetooth-BluetoothHDP
%files sub2-domain_API-Network_Bluetooth-BluetoothHDP


%package sub2-domain_API-Network_Bluetooth-BluetoothHID
Summary:	Network - Bluetooth - Bluetooth HID
Requires:	capi-network-bluetooth
Requires:	bluez
Requires:	bluetooth-tools
Suggests:	bluetooth-frimware-bcm
Suggests:	bluetooth-firmware-sprd
%description sub2-domain_API-Network_Bluetooth-BluetoothHID
Tizen block (set of packages) for API sets of sub2-domain_API-Network_Bluetooth-BluetoothHID
%files sub2-domain_API-Network_Bluetooth-BluetoothHID


%package sub2-domain_API-Network_Bluetooth-BluetoothLEAdapter
Summary:	Network - Bluetooth - Bluetooth LE Adapter
Requires:	capi-network-bluetooth
Requires:	bluez
Requires:	bluetooth-tools
Suggests:	bluetooth-frimware-bcm
Suggests:	bluetooth-firmware-sprd
%description sub2-domain_API-Network_Bluetooth-BluetoothLEAdapter
Tizen block (set of packages) for API sets of sub2-domain_API-Network_Bluetooth-BluetoothLEAdapter
%files sub2-domain_API-Network_Bluetooth-BluetoothLEAdapter


%package sub2-domain_API-Network_Bluetooth-BluetoothOPP
Summary:	Network - Bluetooth - Bluetooth OPP
Requires:	capi-network-bluetooth
Requires:	bluez
Requires:	bluetooth-tools
Suggests:	bluetooth-frimware-bcm
Suggests:	bluetooth-firmware-sprd
%description sub2-domain_API-Network_Bluetooth-BluetoothOPP
Tizen block (set of packages) for API sets of sub2-domain_API-Network_Bluetooth-BluetoothOPP
%files sub2-domain_API-Network_Bluetooth-BluetoothOPP


%package sub2-domain_API-Network_Bluetooth-BluetoothSocket
Summary:	Network - Bluetooth - Bluetooth Socket
Requires:	capi-network-bluetooth
Requires:	bluez
Requires:	bluetooth-tools
Suggests:	bluetooth-frimware-bcm
Suggests:	bluetooth-firmware-sprd
%description sub2-domain_API-Network_Bluetooth-BluetoothSocket
Tizen block (set of packages) for API sets of sub2-domain_API-Network_Bluetooth-BluetoothSocket
%files sub2-domain_API-Network_Bluetooth-BluetoothSocket


%package sub1-domain_API-Network_ASP
Summary:	Network - ASP
Requires:	capi-network-asp
Requires:	asp-manager
%description sub1-domain_API-Network_ASP
Tizen block (set of packages) for API sets of domain API-Network_ASP
%files sub1-domain_API-Network_ASP


%package sub1-domain_API-Network_Connection
Summary:	Network - Connection
Requires:	capi-network-connection
Requires:	net-config
Requires:	connman
Requires:	wpa_supplicant
%description sub1-domain_API-Network_Connection
Tizen block (set of packages) for API sets of domain API-Network_Connection
%files sub1-domain_API-Network_Connection


%package sub1-domain_API-Network_Curl
Summary:	Network - Curl
Requires:	curl
%description sub1-domain_API-Network_Curl
Tizen block (set of packages) for API sets of domain API-Network_Curl
%files sub1-domain_API-Network_Curl


%package sub1-domain_API-Network_DNSSD
Summary:	Network - DNSSD
Requires:	capi-network-nsd
Requires:	mDNSResponder
%description sub1-domain_API-Network_DNSSD
Tizen block (set of packages) for API sets of domain API-Network_DNSSD
%files sub1-domain_API-Network_DNSSD


%package sub1-domain_API-Network_HTTP
Summary:	Network - HTTP
Requires:	capi-network-http
%description sub1-domain_API-Network_HTTP
Tizen block (set of packages) for API sets of domain API-Network_HTTP
%files sub1-domain_API-Network_HTTP


%package sub1-domain_API-Network_IoTCon
Summary:	Network - IoTCon
Requires:	iotcon
%description sub1-domain_API-Network_IoTCon
Tizen block (set of packages) for API sets of domain API-Network_IoTCon
%files sub1-domain_API-Network_IoTCon


%package sub1-domain_API-Network_MTP
Summary:	Network - MTP
Requires:	capi-network-mtp
Requires:	mtp-initiator
%description sub1-domain_API-Network_MTP
Tizen block (set of packages) for API sets of domain API-Network_MTP
%files sub1-domain_API-Network_MTP


%package sub1-domain_API-Network_NFC
Summary:	Network - NFC
Requires:	capi-network-nfc
Requires:	nfc-manager
%description sub1-domain_API-Network_NFC
Tizen block (set of packages) for API sets of domain API-Network_NFC
%files sub1-domain_API-Network_NFC


%package sub1-domain_API-Network_SSDP
Summary:	Network - SSDP
Requires:	capi-network-nsd
%description sub1-domain_API-Network_SSDP
Tizen block (set of packages) for API sets of domain API-Network_SSDP
%files sub1-domain_API-Network_SSDP


%package sub1-domain_API-Network_Smartcard
Summary:	Network - Smartcard
Requires:	capi-network-smartcard
Requires:	smartcard-service
Suggests:	smartcard-plugin-nfc
Suggests:	smartcard-plugin-uicc
%description sub1-domain_API-Network_Smartcard
Tizen block (set of packages) for API sets of domain API-Network_Smartcard
%files sub1-domain_API-Network_Smartcard


%package sub1-domain_API-Network_VPNService
Summary:	Network - VPN Service
Requires:	capi-vpnsvc
%description sub1-domain_API-Network_VPNService
Tizen block (set of packages) for API sets of domain API-Network_VPNService
%files sub1-domain_API-Network_VPNService


%package sub1-domain_API-Network_WiFi
Summary:	Network - WiFi
Suggests:	%{name}-sub2-domain_API-Network_WiFi-WiFi
Suggests:	%{name}-sub2-domain_API-Network_WiFi-WiFiManager
%description sub1-domain_API-Network_WiFi
Tizen block (set of packages) for API sets of domain API-Network_WiFi
%files sub1-domain_API-Network_WiFi


%package sub2-domain_API-Network_WiFi-WiFi
Summary:	Network - WiFi - WiFi
Requires:	capi-network-wifi
Requires:	net-config
Requires:	connman
Requires:	wpa_supplicant
%description sub2-domain_API-Network_WiFi-WiFi
Tizen block (set of packages) for API sets of sub2-domain_API-Network_WiFi-WiFi
%files sub2-domain_API-Network_WiFi-WiFi


%package sub2-domain_API-Network_WiFi-WiFiManager
Summary:	Network - WiFi - WiFi Manager
Requires:	capi-network-wifi-manager
Requires:	net-config
Requires:	connman
Requires:	wpa_supplicant
%description sub2-domain_API-Network_WiFi-WiFiManager
Tizen block (set of packages) for API sets of sub2-domain_API-Network_WiFi-WiFiManager
%files sub2-domain_API-Network_WiFi-WiFiManager


%package sub1-domain_API-Network_WiFiDirect
Summary:	Network - WiFi Direct
Requires:	capi-network-wifi-direct
Requires:	wifi-direct-manager
Requires:	wpa_supplicant
%description sub1-domain_API-Network_WiFiDirect
Tizen block (set of packages) for API sets of domain API-Network_WiFiDirect
%files sub1-domain_API-Network_WiFiDirect


%package sub1-domain_API-Security_CSR
Summary:	Security - CSR
Requires:	libcsr-framework-client
%description sub1-domain_API-Security_CSR
Tizen block (set of packages) for API sets of domain API-Security_CSR
%files sub1-domain_API-Security_CSR


%package sub1-domain_API-Security_KeyManager
Summary:	Security - KeyManager
Requires:	libkey-manager-client
%description sub1-domain_API-Security_KeyManager
Tizen block (set of packages) for API sets of domain API-Security_KeyManager
%files sub1-domain_API-Security_KeyManager


%package sub1-domain_API-Security_OpenSSL
Summary:	Security - KeyManager
Requires:	libopenssl
%description sub1-domain_API-Security_OpenSSL
Tizen block (set of packages) for API sets of domain API-Security_OpenSSL
%files sub1-domain_API-Security_OpenSSL


%package sub1-domain_API-Security_YACA
Summary:	Security - YACA
Requires:	yaca
%description sub1-domain_API-Security_YACA
Tizen block (set of packages) for API sets of domain API-Security_YACA
%files sub1-domain_API-Security_YACA


%package sub1-domain_API-Social_Calendar
Summary:	Social - Calendar
Requires:	libcalendar-service
Suggests:	contacts-service
%description sub1-domain_API-Social_Calendar
Tizen block (set of packages) for API sets of domain API-Social_Calendar
%files sub1-domain_API-Social_Calendar


%package sub1-domain_API-Social_Contacts
Summary:	Social - Contacts
Requires:	libcontacts-service
%description sub1-domain_API-Social_Contacts
Tizen block (set of packages) for API sets of domain API-Social_Contacts
%files sub1-domain_API-Social_Contacts


%package sub1-domain_API-Social_PhonenumberUtils
Summary:	Social - Phonenumber Utils
Requires:	phonenumber-utils
%description sub1-domain_API-Social_PhonenumberUtils
Tizen block (set of packages) for API sets of domain API-Social_PhonenumberUtils
%files sub1-domain_API-Social_PhonenumberUtils


%package sub1-domain_API-System_MediaKey
Summary:	System - Media Key
Requires:	capi-system-media-key
%description sub1-domain_API-System_MediaKey
Tizen block (set of packages) for API sets of domain API-System_MediaKey
%files sub1-domain_API-System_MediaKey


%package sub1-domain_API-System_RuntimeInformation
Summary:	System - Runtime Information
Requires:	capi-system-runtime-info
Requires:	resourced
Requires:	buxton2
Requires:	dbus
%description sub1-domain_API-System_RuntimeInformation
Tizen block (set of packages) for API sets of domain API-System_RuntimeInformation
%files sub1-domain_API-System_RuntimeInformation


%package sub1-domain_API-System_Sensor
Summary:	System - Sensor
Suggests:	%{name}-sub2-domain_API-System_Sensor-SensorListener
Suggests:	%{name}-sub2-domain_API-System_Sensor-SensorRecorder
Requires:	capi-system-sensor
%description sub1-domain_API-System_Sensor
Tizen block (set of packages) for API sets of domain API-System_Sensor
%files sub1-domain_API-System_Sensor


%package sub2-domain_API-System_Sensor-SensorListener
Summary:	System - Sensor - Sensor Listener
Requires:	sensord
%description sub2-domain_API-System_Sensor-SensorListener
Tizen block (set of packages) for API sets of sub2-domain_API-System_Sensor-SensorListener
%files sub2-domain_API-System_Sensor-SensorListener


%package sub2-domain_API-System_Sensor-SensorRecorder
Summary:	System - Sensor - Sensor Recorder
Requires:	context-sensor-recorder
%description sub2-domain_API-System_Sensor-SensorRecorder
Tizen block (set of packages) for API sets of sub2-domain_API-System_Sensor-SensorRecorder
%files sub2-domain_API-System_Sensor-SensorRecorder


%package sub1-domain_API-System_SystemInformation
Summary:	System - System Information
Requires:	capi-system-info
%description sub1-domain_API-System_SystemInformation
Tizen block (set of packages) for API sets of domain API-System_SystemInformation
%files sub1-domain_API-System_SystemInformation


%package sub1-domain_API-System_dlog
Summary:	System - dlog
Requires:	dlog
%description sub1-domain_API-System_dlog
Tizen block (set of packages) for API sets of domain API-System_dlog
%files sub1-domain_API-System_dlog


%package sub1-domain_API-Telephony
Summary:	Telephony
Requires:	capi-telephony
Requires:	telephony-daemon
Requires:	tel-plugin-dbus_tapi
Requires:	tel-plugin-manager
Requires:	tel-plugin-database
Requires:	tel-plugin-vconf
Suggests:	tel-plugin-packetservice
Suggests:	tel-plugin-nitz
Suggests:	tel-plugin-indicator
Suggests:	telephony-syspopup
Suggests:	tel-plugin-syspopup
%description sub1-domain_API-Telephony
Tizen block (set of packages) for API sets of domain API-Telephony
%files sub1-domain_API-Telephony


%package sub1-domain_API-UI_Cairo
Summary:	UI - Cairo
Requires:	libcairo
%description sub1-domain_API-UI_Cairo
Tizen block (set of packages) for API sets of domain API-UI_Cairo
%files sub1-domain_API-UI_Cairo


%package sub1-domain_API-UI_ClipboardHistoryManager
Summary:	UI - Clipboard History Manager
Requires:	cbhm
%description sub1-domain_API-UI_ClipboardHistoryManager
Tizen block (set of packages) for API sets of domain API-UI_ClipboardHistoryManager
%files sub1-domain_API-UI_ClipboardHistoryManager


%package sub1-domain_API-UI_DALi
Summary:	UI - DALi
Requires:	dali-toolkit
Suggests:	dali-extension
Suggests:	dali-extension-key-extension
Suggests:	%{name}-sub2-domain_API-UI_DALi-DALiAdaptor
Suggests:	%{name}-sub2-domain_API-UI_DALi-DALiCore
Suggests:	%{name}-sub2-domain_API-UI_DALi-DALiToolkit
%description sub1-domain_API-UI_DALi
Tizen block (set of packages) for API sets of domain API-UI_DALi
%files sub1-domain_API-UI_DALi


%package sub2-domain_API-UI_DALi-DALiAdaptor
Summary:	UI - DALi - DALi Adaptor
Requires:	dali-toolkit
Suggests:	dali-adaptor-dali-feedback-plugin
Suggests:	dali-adaptor-dali-video-player-plugin
Suggests:	dali-adaptor-profile_common
Suggests:	dali-adaptor-profile_mobile
Suggests:	dali-adaptor-profile_tv
Suggests:	dali-adaptor-profile_wearable
Suggests:	dali-adaptor-profile_ivi
%description sub2-domain_API-UI_DALi-DALiAdaptor
Tizen block (set of packages) for API sets of sub2-domain_API-UI_DALi-DALiAdaptor
%files sub2-domain_API-UI_DALi-DALiAdaptor


%package sub2-domain_API-UI_DALi-DALiCore
Summary:	UI - DALi - DALi Core
Requires:	dali-toolkit
%description sub2-domain_API-UI_DALi-DALiCore
Tizen block (set of packages) for API sets of sub2-domain_API-UI_DALi-DALiCore
%files sub2-domain_API-UI_DALi-DALiCore


%package sub2-domain_API-UI_DALi-DALiToolkit
Summary:	UI - DALi - DALi Toolkit
Requires:	dali-toolkit
Suggests:	dali-toolkit-resources_480x800
Suggests:	dali-toolkit-resources_720x1280
Suggests:	dali-toolkit-resources_1920x1080
%description sub2-domain_API-UI_DALi-DALiToolkit
Tizen block (set of packages) for API sets of sub2-domain_API-UI_DALi-DALiToolkit
%files sub2-domain_API-UI_DALi-DALiToolkit


%package sub1-domain_API-UI_EFL
Summary:	UI - EFL
Suggests:	%{name}-sub2-domain_API-UI_EFL-Ecore
Suggests:	%{name}-sub2-domain_API-UI_EFL-Edje
Suggests:	%{name}-sub2-domain_API-UI_EFL-Eet
Suggests:	%{name}-sub2-domain_API-UI_EFL-Eina
Suggests:	%{name}-sub2-domain_API-UI_EFL-Eio
Suggests:	%{name}-sub2-domain_API-UI_EFL-Eldbus
Suggests:	%{name}-sub2-domain_API-UI_EFL-Elementary
Suggests:	%{name}-sub2-domain_API-UI_EFL-Evas
Requires:	efl
Requires:	eo
%description sub1-domain_API-UI_EFL
Tizen block (set of packages) for API sets of domain API-UI_EFL
%files sub1-domain_API-UI_EFL


%package sub2-domain_API-UI_EFL-Ecore
Summary:	UI - EFL - Ecore
Requires:	ecore-core
Requires:	ecore-input
Requires:	ecore-buffer
Requires:	ecore-con
Requires:	ecore-evas
Requires:	ecore-file
Requires:	ecore-imf
Requires:	ecore-ipc
Suggests:	ecore
%description sub2-domain_API-UI_EFL-Ecore
Tizen block (set of packages) for API sets of sub2-domain_API-UI_EFL-Ecore
%files sub2-domain_API-UI_EFL-Ecore


%package sub2-domain_API-UI_EFL-Edje
Summary:	UI - EFL - Edje
Requires:	edje
%description sub2-domain_API-UI_EFL-Edje
Tizen block (set of packages) for API sets of sub2-domain_API-UI_EFL-Edje
%files sub2-domain_API-UI_EFL-Edje


%package sub2-domain_API-UI_EFL-Eet
Summary:	UI - EFL - Eet
Requires:	eet
%description sub2-domain_API-UI_EFL-Eet
Tizen block (set of packages) for API sets of sub2-domain_API-UI_EFL-Eet
%files sub2-domain_API-UI_EFL-Eet


%package sub2-domain_API-UI_EFL-Eina
Summary:	UI - EFL - Eina
Requires:	eina
%description sub2-domain_API-UI_EFL-Eina
Tizen block (set of packages) for API sets of sub2-domain_API-UI_EFL-Eina
%files sub2-domain_API-UI_EFL-Eina


%package sub2-domain_API-UI_EFL-Eio
Summary:	UI - EFL - Eio
Requires:	eio
%description sub2-domain_API-UI_EFL-Eio
Tizen block (set of packages) for API sets of sub2-domain_API-UI_EFL-Eio
%files sub2-domain_API-UI_EFL-Eio


%package sub2-domain_API-UI_EFL-Eldbus
Summary:	UI - EFL - Eldbus
Requires:	eldbus
%description sub2-domain_API-UI_EFL-Eldbus
Tizen block (set of packages) for API sets of sub2-domain_API-UI_EFL-Eldbus
%files sub2-domain_API-UI_EFL-Eldbus


%package sub2-domain_API-UI_EFL-Elementary
Summary:	UI - EFL - Elementary
Requires:	elementary
Requires:	efl-theme-tizen-common
Requires:	efl-config-profile_common
Requires:	efl-misc-profile_common
Requires:	efl-modules-profile_common
Suggests:	elementary-tizen
Suggests:	efl-theme-tizen-ivi
Suggests:	efl-theme-tizen-mobile
Suggests:	efl-theme-tizen-wearable
Suggests:	efl-theme-tizen-tv
Suggests:	efl-config-profile_ivi
Suggests:	efl-config-profile_mobile
Suggests:	efl-config-profile_wearable
Suggests:	efl-config-profile_tv
Suggests:	efl-misc-profile_ivi
Suggests:	efl-misc-profile_mobile
Suggests:	efl-misc-profile_wearable
Suggests:	efl-misc-profile_tv
Suggests:	efl-modules-profile_ivi
Suggests:	efl-modules-profile_mobile
Suggests:	efl-modules-profile_wearable
Suggests:	efl-modules-profile_tv
%description sub2-domain_API-UI_EFL-Elementary
Tizen block (set of packages) for API sets of sub2-domain_API-UI_EFL-Elementary
%files sub2-domain_API-UI_EFL-Elementary


%package sub2-domain_API-UI_EFL-Evas
Summary:	UI - EFL - Evas
Requires:	evas
%description sub2-domain_API-UI_EFL-Evas
Tizen block (set of packages) for API sets of sub2-domain_API-UI_EFL-Evas
%files sub2-domain_API-UI_EFL-Evas


%package sub1-domain_API-UI_EFLUTIL
Summary:	UI - EFL UTIL
Requires:	capi-ui-efl-util
%description sub1-domain_API-UI_EFLUTIL
Tizen block (set of packages) for API sets of domain API-UI_EFLUTIL
%files sub1-domain_API-UI_EFLUTIL


%package sub1-domain_API-UI_EflExtension
Summary:	UI - Efl Extension
Requires:	efl-extension
%description sub1-domain_API-UI_EflExtension
Tizen block (set of packages) for API sets of domain API-UI_EflExtension
%files sub1-domain_API-UI_EflExtension


%package sub1-domain_API-UI_ExternalOutputManager
Summary:	UI - External Output Manager
Requires:	libeom
Suggests:	libeom-server
Suggests:	e-mod-tizen-eom
%description sub1-domain_API-UI_ExternalOutputManager
Tizen block (set of packages) for API sets of domain API-UI_ExternalOutputManager
%files sub1-domain_API-UI_ExternalOutputManager


%package sub1-domain_API-UI_FontConfig
Summary:	UI - FontConfig
Requires:	fontconfig
Requires:	default-fonts-fc-sdk
Requires:	default-fonts-sdk
%description sub1-domain_API-UI_FontConfig
Tizen block (set of packages) for API sets of domain API-UI_FontConfig
%files sub1-domain_API-UI_FontConfig


%package sub1-domain_API-UI_Freetype
Summary:	UI - Freetype
Requires:	freetype
%description sub1-domain_API-UI_Freetype
Tizen block (set of packages) for API sets of domain API-UI_Freetype
%files sub1-domain_API-UI_Freetype


%package sub1-domain_API-UI_HarfBuzz
Summary:	UI - HarfBuzz
Requires:	harfbuzz
%description sub1-domain_API-UI_HarfBuzz
Tizen block (set of packages) for API sets of domain API-UI_HarfBuzz
%files sub1-domain_API-UI_HarfBuzz


%package sub1-domain_API-UI_SDL
Summary:	UI - SDL
Requires:	SDL2
%description sub1-domain_API-UI_SDL
Tizen block (set of packages) for API sets of domain API-UI_SDL
%files sub1-domain_API-UI_SDL


%package sub1-domain_API-UI_TBMSurface
Summary:	UI - TBM Surface
Requires:	libtbm
Suggests:	libtbm-exynos
Suggests:	libtbm-sprd
Suggests:	libtbm-vigs
Suggests:	libtbm-vc4
%description sub1-domain_API-UI_TBMSurface
Tizen block (set of packages) for API sets of domain API-UI_TBMSurface
%files sub1-domain_API-UI_TBMSurface


%package sub1-domain_API-UI_TizenWSShell
Summary:	UI - Tizen WS Shell
Requires:	tzsh
%description sub1-domain_API-UI_TizenWSShell
Tizen block (set of packages) for API sets of domain API-UI_TizenWSShell
%files sub1-domain_API-UI_TizenWSShell


%package sub1-domain_API-UI_UIViewManager
Summary:	UI - UI View Manager
Requires:	ui-viewmgr
%description sub1-domain_API-UI_UIViewManager
Tizen block (set of packages) for API sets of domain API-UI_UIViewManager
%files sub1-domain_API-UI_UIViewManager


%package sub1-domain_API-UIX_InputMethod
Summary:	UIX - Input Method
Requires:	capi-ui-inputmethod
%description sub1-domain_API-UIX_InputMethod
Tizen block (set of packages) for API sets of domain API-UIX_InputMethod
%files sub1-domain_API-UIX_InputMethod


%package sub1-domain_API-UIX_InputMethodManager
Summary:	UIX - Input Method Manager
Requires:	capi-ui-inputmethod-manager
%description sub1-domain_API-UIX_InputMethodManager
Tizen block (set of packages) for API sets of domain API-UIX_InputMethodManager
%files sub1-domain_API-UIX_InputMethodManager


%package sub1-domain_API-Web
Summary:	Web
Requires:	chromium-efl
%description sub1-domain_API-Web
Tizen block (set of packages) for API sets of domain API-Web
%files sub1-domain_API-Web