# Maintainer: TBD: This is temporary block for TDC Demo. You may proceed with this later anyway.
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

%package root-domain_Feature
Summary:	Tizen Platform Internal Feature Sets
Suggests:	%{name}-sub1-domain_Feature-DotNET
Suggests:	%{name}-sub1-domain_Feature-WebAPI
Suggests:	%{name}-sub1-domain_Feature-BootAni
Suggests:	%{name}-sub1-domain_Feature-Starter
Suggests:	%{name}-sub1-domain_Feature-Upgrade
Suggests:	%{name}-sub1-domain_Feature-Recovery
Suggests:	%{name}-sub1-domain_Feature-Setup
Suggests:	%{name}-sub1-domain_Feature-Tool_And_Locale
Suggests:	%{name}-sub1-domain_Feature-Resource_manager
Suggests:	%{name}-sub1-domain_Feature-Resource_manager_Light
Suggests:	%{name}-sub1-domain_Feature-Resource_manager_Headless
Suggests:	%{name}-sub1-domain_Feature-Smartthings_App

%description root-domain_Feature
__EXPAND__: domains
Tizen Platform Internal Feature Sets
%files root-domain_Feature

