# Maintainer: TBD: This is temporary block for TDC Demo. You may proceed with this later anyway.
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.

####################
## Boot Animation ##
####################
%package sub1-domain_Feature-BootAni
Summary:	Boot Animation packages
Requires: boot-animation
Requires: boot-animation-sound-file-profile_common
%description sub1-domain_Feature-BootAni
Tizen block (set of packages) for Boot Animation of Tizen
%files sub1-domain_Feature-BootAni
