# Maintainer: Tizen Home Appliance PM
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.


%package root-preset_home_appliance
Summary:	Common Profile Presets
Conflicts:	%{name}-root-preset_mobile
Conflicts:	%{name}-root-preset_tv
Conflicts:	%{name}-root-preset_wearable
Conflicts:	%{name}-root-preset_iot
Conflicts:	%{name}-root-preset_ivi
Conflicts:	%{name}-root-preset_common
%description root-preset_home_appliance
Tizen Platform Presets for "Home Appliances"
%files root-preset_home_appliance
