# Maintainer: Tizen Home Appliance PM
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.


%package root-preset-home_appliance
Summary:	Common Profile Presets
Conflicts:	%{name}-root-preset-mobile
Conflicts:	%{name}-root-preset-tv
Conflicts:	%{name}-root-preset-wearable
Conflicts:	%{name}-root-preset-iot
Conflicts:	%{name}-root-preset-ivi
Conflicts:	%{name}-root-preset-common
%description root-preset-home_appliance
Tizen Platform Presets for "Home Appliances"
%files root-preset-home_appliance
