# Maintainer: Tizen Common PM
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.


%package sub1-preset-common
Summary:	Common Profile Presets
Conflicts:	%{name}-sub1-preset-mobile
Conflicts:	%{name}-sub1-preset-tv
Conflicts:	%{name}-sub1-preset-wearable
Conflicts:	%{name}-sub1-preset-iot
Conflicts:	%{name}-sub1-preset-ivi
%description sub1-preset-common
Tizen Platform Presets for "Common Profile"
%files sub1-preset-common
