# Maintainer: Tizen Common PM
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.


%package root-preset_common
Summary:	Common Profile Presets
Conflicts:	%{name}-root-preset_mobile
Conflicts:	%{name}-root-preset_tv
Conflicts:	%{name}-root-preset_wearable
Conflicts:	%{name}-root-preset_iot
Conflicts:	%{name}-root-preset_ivi
%description root-preset_common
Tizen Platform Presets for "Common Profile"
%files root-preset_common
