# Maintainer: Tizen Home Appliance PM
# You need ACK (+1) from the maintainer to be reviewed by building-blocks maintainers.


%package sub1-preset-home_appliance
Summary:	Common Profile Presets
Conflicts:	%{name}-sub1-preset-mobile
Conflicts:	%{name}-sub1-preset-tv
Conflicts:	%{name}-sub1-preset-wearable
Conflicts:	%{name}-sub1-preset-iot
Conflicts:	%{name}-sub1-preset-ivi
Conflicts:	%{name}-sub1-preset-common
%description sub1-preset-home_appliance
Tizen Platform Presets for "Home Appliances"
%files sub1-preset-home_appliance
